# Generated by Django 4.2.30 on 2026-05-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_appointment_cancellation_reason'),
        ('cars', '0007_seller_logo_review_conversation_message'),
    ]

    operations = [
    ]
