# Generated by Django 4.2.30 on 2026-05-31 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0008_merge_20260531_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirme'), ('rejected', 'Refuse'), ('cancelled', 'Annule'), ('active', 'En cours'), ('completed', 'Termine')], default='pending', max_length=20)),
                ('renter_message', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rental_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_reviewer_seller',
        ),
        migrations.AddField(
            model_name='car',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Vente uniquement'), ('rental', 'Location uniquement'), ('both', 'Vente et Location')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='rental_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='rental_min_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='rental_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='rental_required_docs',
            field=models.JSONField(blank=True, default=list, help_text="Liste des documents exigés (ex: ['Permis de conduire', 'CIN'])"),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'seller')},
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='cars.car'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='cars.seller'),
        ),
    ]
