# Generated by Django 4.2.30 on 2026-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_review_rating_range'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_available', '-created_at'], name='cars_is_avai_8afcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_available', 'price'], name='cars_is_avai_840557_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['listing_type'], name='cars_listing_7d5a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalrequest',
            index=models.Index(fields=['car', 'status'], name='rental_requ_car_id_b0d097_idx'),
        ),
    ]
