# Generated by Django 4.2.30 on 2026-06-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_appointment_appointment_status_9fecd6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='premium_expiry_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='premium_renewal_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_command', models.CharField(max_length=64, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Montant en FCFA, fixé côté serveur')),
                ('months', models.PositiveSmallIntegerField(default=1)),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Payé'), ('cancelled', 'Annulé'), ('failed', 'Échec')], default='pending', max_length=12)),
                ('token', models.CharField(blank=True, max_length=128)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('cgu_accepted', models.BooleanField(default=False)),
                ('cgu_version', models.CharField(blank=True, max_length=20)),
                ('cgu_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_payments', to='cars.seller')),
            ],
            options={
                'db_table': 'premium_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', '-created_at'], name='premium_pay_seller__1e6986_idx'), models.Index(fields=['status'], name='premium_pay_status_f7988c_idx')],
            },
        ),
    ]
