# Generated by Django 4.2.30 on 2026-07-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_seller_premium_expiry_notified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
