# Generated by Django 4.2.30 on 2026-06-02 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cni_maxlength_17'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_number',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numero de CNI doit contenir exactement 13 chiffres.', regex='^\\d{13}$')], verbose_name='Numero CNI'),
        ),
    ]
