# Generated by Django 4.2.30 on 2026-06-08 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_id_card_number_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_number',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='CNI invalide : 13 ou 17 chiffres, commencant par 1 (homme) ou 2 (femme).', regex='^[12]\\d{12}$|^[12]\\d{16}$')], verbose_name='Numero CNI'),
        ),
    ]
