# Generated by Django 4.2.30 on 2026-06-13 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_emailverification_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment_new', 'Nouveau rendez-vous'), ('appointment_confirmed', 'Rendez-vous confirmé'), ('appointment_cancelled', 'Rendez-vous annulé'), ('appointment_completed', 'Rendez-vous terminé'), ('new_review', 'Nouvel avis'), ('new_message', 'Nouveau message'), ('rental_request', 'Demande de location'), ('rental_update', 'Mise à jour location')], max_length=30),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_resets',
            },
        ),
    ]
