# Generated by Django 4.2.30 on 2026-06-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_notification_type_passwordreset'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'is_used', '-created_at'], name='email_verif_user_id_956ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['user', 'is_used', '-created_at'], name='password_re_user_id_aa2444_idx'),
        ),
    ]
